name: Autograding Tests
'on':
  - push
  - repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run custom grader
        id: custom-grader
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: custom grader
          setup-command: ''
          command: python3 tests/custom_grader.py
          timeout: 10
          max-score: 300  # ✅ Updated to reflect actual max total

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          CUSTOM_GRADER_RESULTS: "${{ steps.custom-grader.outputs.result }}"
        with:
          runners: custom_grader
